# Generated by Django 6.0.4 on 2026-04-25 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_acnepredictionmodel_annotated_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='acnepredictionmodel',
            name='model_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
