# Generated by Django 5.0.6 on 2026-05-16 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_acnepredictionmodel_model_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistrationmodel',
            name='approve_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
