# Generated by Django 6.0.5 on 2026-06-11 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passwordresetotp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acnepredictionmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.userregistrationmodel'),
        ),
    ]
