# Generated by Django 6.0.5 on 2026-06-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_acnepredictionmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='acnepredictionmodel',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
